### ISSUE TITLE
Why would install_sources need to clone sources from remote? Though we have cached with cocoapods itself？

### ISSUE THREAD

**Issue by chml** [Subito-it/PodBuilder#29]

**Comment by tcamin** [comment]
Because if PodA is prebuilt then no sources for PodA will be downloaded to the Pods folder.

**Comment by Nytecaster** [comment]
I believe the question is related to fetching from remote if there is already a stored local cache.  This is highly desired in CI systems especially since a lot of times you are running tasks in parallel and possibly on multiple slaves.  Anything that can be cached saves time, bandwidth and resources.

**Comment by chml** [comment]
> Because if PodA is prebuilt then no sources for PodA will be downloaded to the Pods folder.

I just start try this out; And I pretty sure my CocoaPods cache do have cached PodA's source code, But when I run 'pod_builder install_sources' it still kick off network to download the source.

**Comment by tcamin** [comment]
CocoaPods does not clean the Pod folder cache. try running `pod deintegrate; pod install` and you should see the PodA cache disappear
