### ISSUE TITLE
vendored_libraries did not static linked in framework

### ISSUE THREAD

**Issue by chml** [Subito-it/PodBuilder#37]
`vendored_libraries` (.a files) should linked in the pod production framework, which Cocoapods does, but PodBuilder prebuild does not.

**Comment by chml** [comment]
demo: https://github.com/chml/BuilderTest.git

**Comment by tcamin** [comment]
You’re trying to use a static library as a transient dependency which as far as I know is not the way vendored_libraries should be used because you can end up with duplicated symbols. Instead vendored_libraries should include dependencies required to build the pod (in your case BuildTest).

If you really want to “proxy” libWeChat library symbols (instead of simply adding libWeChat to your main app) you can change the podspec as follows:

```
  s.public_header_files = 'BuilderTest/Classes/OpenSDK/*.h'
  s.xcconfig = { "OTHER_LDFLAGS" => "-all_load" }
  s.frameworks = 'UIKit', 'WebKit'
```

**Comment by chml** [comment]
Yes, `-all_load` flag is helpful, thank you.
I'm closing this.
